kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 1.2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    type: DirectoryOrCreate
    path: "/data/nginx"